spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chargeevent
    username: root
    password: ZCYaghm13@
  web:
    resources:
      static-locations: file:///D:/Project/
mybatis:
  configuration:
    map-underscore-to-camel-case: true
